### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by LaLeonie** [fac-17/Autsera#1]
- As a user,  I want to see the progress of the game
- As a user, I want to choose my character
- As a user, I want to collect rewards/trophies
- As a user, I want to play in different scenes that I am familiar with (playground, school, birthday party)
- As a user, I want structure, repetition and consistency
- As a user, I want a clear beginning and a clear end
- As a user, I need to be given a limited time per day to play the game (chosen by the parents)
- As a user, I want to get a notification before my time runs out
- As a user, I want to review my progress
- As a user, I want a helper avatar to give me hints when I'm stuck, explain the game to me and keep me motivated
- As a user, I want an explainer video at the start that shows me how this game is played
- As a user, I want visual and audio stimulation, but I want the game to work without audio
- As a user, I want to acquire friends as I progress in the game
- As a user, I want to decide my own path within the lower level scene (playground etc)
- As a user, I want the scenes to become more difficult as I progress through the game
- As a user, I want to be able to repeat the same challenges multiple times
- As a user, I want to play the game on a tablet

Optional/to be discussed: 
- As a user, I want to be given a predefined route on the top level (city)

**Comment by LaLeonie** [comment]
**User Stories for parents/caretakers**

- As a caretaker, I want to be able to set a playing time limit per day 
- As a caretaker, I want to see the progress of the player 
- As a caretaker, I want to be able to log in as a parent/caretaker with an authentification code 
- As a caretaker, I want to be able to set the repetitions

**Comment by victormasson21** [comment]
## User Stories 
Updated to separate core goals and stretch goals.

### Core Goal 

- As a user  I want to see the progress of the game
- As a user I want to play in different scenes that I am familiar with (playground, school, birthday party)
- As a user I want structure, repetition and consistency, with a clear beginning and a clear end.
- As a user I want to have options, but not too many. (show one interaction first, then unlock more as they finish)
- As a user I want a helper avatar to give me hints when I'm stuck, explain the game to me and keep me motivated.
- As a user, I want access to an explainer page at the start (featuring an explainer video and/or bullet points)
- As a user I want to decide my own path within the lower level scene (playground etc) 
- As a user, I want to play the game on a tablet

### Stretch Goal 

- As a user I want to choose my character.
- As a user I need to be given a limited time per day to play the game (chosen by the parents).
- As a user I want to get a notification before my time runs out.
- As a user I want to collect rewards/trophees.
- As a user I want to acquire friends as I progress in the game
- As a carer I want to review my progress.
- As a user I want visual and audio stimulation, but I want the game to work without audio
- As a user I want the scenes to become more difficult as I progress through the game (dependent on content)
