### ISSUE TITLE
Format for Interactions - For POs to refer to as templates

### ISSUE THREAD

**Issue by reubengt** [fac-17/Autsera#4]
# Format for Interactions

## 1. Interaction Title

Image for the interaction

## 2. Options - Multiple emotions to select from
- Emotion:
  - **If wrong:** Text asking player to look closer at a specific facial feature
  - **If right:** Confirmation message

-------------
# Example

## Lisa and Suzi

Image of a Situation of two girls playing

- Image asset 

## Options 

- **Arguing** - Look at ther eyes, are they smiling.
- (+) **Happy** - Correct, they are smiling and happy.
- **Sad** - Look at ther eyes, are they smiling.
- **Bored** - Do they look like they have a lot of energy
- (+) **Focused** - Correct!
- (+) **Interested** - Correct!
- **Tired** - Do they look like they have a lot of energy
- **Angry** - Look at ther eyes, are they smiling.

**Comment by crianonim** [comment]
Example of interaction
![Interaction](https://user-images.githubusercontent.com/13589494/65973401-2ed33680-e463-11e9-8277-2cd0ad408b84.png)
