### ISSUE TITLE
MVP focus

### ISSUE THREAD

**Issue by Inasova** [fac-17/Autsera#61]
Hello coders,

Sorry for the late message. No pressure to respond tonight. Please discuss and let me know when is convenient.

I have a dilemma about choosing different interactions within the same place.

Now, the idea was to look at people within different interactions exhibiting different facial expressions. We also liked the idea of unlocking the picture bit by by. In the mock-up testing, you started by the two girls in the sand pit. Now, if I look at the rest of this picture (attached), all facial expressions are similar. Happy, engaged, etc.. So, we can not reflect variety. Of course, in later stages we will need an illustrator/artist on board, to interpret the scanarios we want to include in one picture (place).

![vector-illustration-of-happy-children-playing-in-playground-1099688924](https://user-images.githubusercontent.com/36169764/66341738-ccd17000-e93f-11e9-8e69-419c7a61cea7.jpg)

What do you think about:
1) making the MVP, 1 scenario in each place in the map?
So. rather than unlocking many interactions in one place, we unlock places on the map.

2) If we stay in the same place, we can move on to more difficult questions. So, rather than just reading facial expressions, we can start asking: "what do you think they will do next? 1- solve their homework. 2- build a sand castle? 3- put on their coats.
but this won't allow us to see/test unlocking worlds.

Or 3) a combination of both: 2 degrees of difficulty focusing on 1 interaction as in 2),  plus doing that in 3 or 4 places, unlocking the places as we progress as in 1)

Please advice to get suitable content/questions

**Comment by victormasson21** [comment]
Hello Inas & Omar, apologies for the delay in getting back!

Your comment raises a very good isse and we had a long chat about it yesterday and again this morning with the team.

We agree that having a wide range of "places" will make things more varied and interesting.

However we'd also like to keep the option of having multiple "interactions" available in each place: if we don't then there will only be one level of depth to the game (as in: you look at the map, go to a place, solve it and come right back to the map) which could be a bit simple and boring for the players in the long term.

To make sure the interactions in each "place" aren't too repetitive we could play with difficulty - so present a similar situation but with a tricker question... So essentially going with the 3rd option you suggested above.

In any case, the app is being built in a way that will allow complete flexibility with how many "places" are available, and how many "interactions" are available in each place. So for example you could have an interesting place (like the school playground) with 10 interactions, and a whole lot of less interesting places (the shop, a bus) with a single interaction available...This will depend on what content is written, designed, etc.

Let us know your thoughts and if this sounds all good to you!

We have made some good progress this week already and are optimistic abour being able to deliver an MVP by the end of next week :)
